1. What does Pandas stand for?
    - Panel Data or Python Data Analysis

2. What are the 2 collections used in Pandas?
    - Lists and Dictionaries
3. Name 4 things Pandas can do for us.
    - Data Cleansing
    - Data fill
    - Merges and joins
    - Data inspection
4. To permanently sort a DataFrame, which keyword should one use with the df.sort() method?

5. What is a CSV?
 - A CSV is a file type containing data, typically separated by commas
6. When cleaning data what values do we not like in our data?
    - Null values

# Coding Exercise


1. Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method

In [36]:
import numpy as np
import pandas as pd

arrayEX = np.array([[1, 4, 5], [6, 7, 9]])
# arrayEX.reshape(2,3)

2. Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20

In [48]:
a1 = np.linspace(0, 20, num=6)

3. Make a Deep Copy of the above array

In [49]:
a1Copy = np.copy(a1)

4. Concatenate these 3 arrays into a new array named 'newArray'...

In [51]:
a2 = np.array([[25,16]])
a3 = np.array([[11,2], [13,4]])
a4 = np.array([[7,81],[5,6], [11,12]])

newArray = np.concatenate((a2, a3, a4))

5. Sort 'newArray' in order into 'sortedArray'

In [53]:
sortedArray = np.sort(newArray)
print(sortedArray)

[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


6. Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.

7. Combined and sort the following arrays into one called 'comboArray' ...

In [69]:
one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = one + two + three
comboArray = np.sort(comboArray)
print(comboArray)

[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


8. Take 'comboArray' and perform the following slicing activities:

    - print sec1 - the 2nd element
    - print sec2 - all elements from the 3rd element to the last
    - print sec3 - all elements from the 4th to the 14th elements
    - print sec4 - the last 6 elements
    - print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
    - print sec6 - from #20 every even element to the end
    - print sec7 - from the last element moving forward, every 5th element.

In [78]:
print(comboArray)
print(comboArray[2])
print(comboArray[3:-1])
print(comboArray[4:14])
print(comboArray[-7:-1])
print(comboArray[0:-10])
print(comboArray[20:-1:2])
# print(comboArray[-1:0:5])


[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
2
[ 3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26]
[ 4  5  6  7 10 11 12 13 14 15]
[21 22 23 24 25 26]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
[24 26]
[]


8. Using Series, create a DataFrame that looks like this:

    | Ingredients | Quantity | Unit |
    |----|----|----|
    | Flour | 4 | cups |
    | Milk | 1 | cup |
    | Eggs | 2 | large |
    | Spam | 1 | can |

In [111]:
ingredients = pd.Series(['Flour', 'Milk', 'Eggs', 'Spam'])
quantity = pd.Series([4, 1, 2, 1])
unit = pd.Series(['cups', 'cup', 'large', 'can'])

df = pd.DataFrame({'Ingredients' : ingredients, 'Quantity' : quantity, 'Unit' : unit})


TypeError: Index(...) must be called with a collection of some kind, False was passed

8. Take this data and create a DataFrame named studentData

In [98]:
studentData = pd.DataFrame(
    {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
    }
    )

deserts = (['ice cream', 'Cashew Fudge', 'waffels', 'Carrot Halwa'])
studentData['deserts'] = deserts
print(studentData)

Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket

9. Add a new column to the DataFrame with the following deserts: ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

In [99]:
deserts = (['ice cream', 'Cashew Fudge', 'waffels', 'Carrot Halwa'])
studentData['deserts'] = deserts
print(studentData)

      Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

        deserts  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa  


10. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

In [104]:
studentData.groupby('Name')['address']

11. Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:

In [106]:
  df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
df.to_csv('cows_and_goats.csv')

12. (A) Using Pandas, make your own .CSV file with data on vegetables and save it. (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.

In [110]:
vegetables = pd.DataFrame(
    [['Pepper', 'Green'],
     ['Carrot', 'Orange'],
     ['Onion', 'Purple']],
     
     columns=['Name', 'Color'])

vegetables.to_csv('VegetableTable.csv')

vegetablesDF = pd.read_csv('VegetableTable.csv')

print(vegetablesDF)

   Unnamed: 0    Name   Color
0           0  Pepper   Green
1           1  Carrot  Orange
2           2   Onion  Purple
